質問の入力フォームを作成する
nekochans/love-psychology-web pull request #20
Opened 2020-01-13 10:25 UTC by kobayashi-m42

# issueURL
https://github.com/nekochans/love-psychology-web/issues/12

# Doneの定義
https://github.com/nekochans/love-psychology-web/issues/12 の完了の定義が満たされていること

# スクリーンショット
[optional] ただしUI変更の時は [required]

# 変更点概要

## 仕様的変更点概要
[optional]

## 技術的変更点概要
[required]

# レビュアーに重点的にチェックして欲しい点
[optional]

# 補足情報
[optional]

2020-01-19 09:09 UTC, keitakn requested changes
対応ありがとう🐱！回答と結果までの流れはこれで良いと思う👍

あとComponentとかURLも良いと思う👌

何点か細かい点でコメントしたから、また時間ある時に確認よろしく！

2020-01-19 09:09 UTC, keitakn commented on src/features/analysis/analysisSlice.ts
> +      });
これでもいいんだけど自分だったらスプレッド構文を使ってこうするかも🐱！

```
      return {
        ...state,
        questions: action.payload,
        answers,
        isLoading: false,
        errorMessage: ''
      };
```

配列の場合も同じ構文で利用出来るのと、コーディング規約によってはこっちを優先しているケースもあるから、このケースだとスプレッド構文を優先で良いかも！

2020-01-19 09:09 UTC, keitakn commented on src/features/analysis/analysisSlice.ts
> +      });
ここもスプレッド構文を優先して↓としたほうが良いかも🐱

```
return { ...state, answers, disableNextButton };
```

2020-01-19 09:09 UTC, keitakn commented on src/features/analysis/analysisSlice.ts
> +      let disableNextButton = true;
原則として `let` より `const` を使いたいから宣言位置を `const answeredList` より下にして `const disableNextButton = answeredList.indexOf(false) !== -1;` とすると `const` で宣言出来るからこのほうが良いかも🐱

2020-01-19 09:09 UTC, keitakn commented on src/features/analysis/analysisSlice.ts
> +      return Object.assign(state, {
ここもスプレッド構文で書き換えたほうが良いかも🐱

2020-01-20 04:05 UTC, kobayashi-m42 commented
@keitakn レビューありがとう！
`Object.assign()`と`let`を使わないように修正したよ！

2020-01-20 04:28 UTC, keitakn approved these changes

2020-01-20 04:30 UTC, merged